// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dt_report.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DTReport _$DTReportFromJson(Map<String, dynamic> json) => DTReport(
      ID: json['ID'] as int?,
      TeamName: json['TeamName'] as String?,
      TeamTEL: json['TeamTEL'] as String?,
      TeamCaptainName: json['TeamCaptainName'] as String?,
      LifesaverQualification: json['LifesaverQualification'] as int?,
      WithLifeSavers: json['WithLifeSavers'] as int?,
      TeamMemberName: json['TeamMemberName'] as String?,
      InstitutionalMemberName: json['InstitutionalMemberName'] as String?,
      Total: json['Total'] as int?,
      Team: json['Team'] as int?,
      SickInjuredPersonName: json['SickInjuredPersonName'] as String?,
      SickInjuredPersonKANA: json['SickInjuredPersonKANA'] as String?,
      SickInjuredPersonAddress: json['SickInjuredPersonAddress'] as String?,
      SickInjuredPersonGender: json['SickInjuredPersonGender'] as String?,
      SickInjuredPersonBirthDate: json['SickInjuredPersonBirthDate'] as String?,
      SickInjuredPersonTEL: json['SickInjuredPersonTEL'] as String?,
      SickInjuredPersonFamilyTEL: json['SickInjuredPersonFamilyTEL'] as String?,
      SickInjuredPersonMedicalHistroy:
          json['SickInjuredPersonMedicalHistroy'] as String?,
      SickInjuredPersonHistoryHospital:
          json['SickInjuredPersonHistoryHospital'] as String?,
      SickInjuredPersonKakaritsuke:
          json['SickInjuredPersonKakaritsuke'] as String?,
      SickInjuredPersonMedication:
          json['SickInjuredPersonMedication'] as String?,
      SickInjuredPersonMedicationDetail:
          json['SickInjuredPersonMedicationDetail'] as String?,
      SickInjuredPersonAllergy: json['SickInjuredPersonAllergy'] as String?,
      SickInjuredPersonNameOfInjuaryOrSickness:
          json['SickInjuredPersonNameOfInjuaryOrSickness'] as String?,
      SickInjuredPersonDegree: json['SickInjuredPersonDegree'] as String?,
      SickInjuredPersonAge: json['SickInjuredPersonAge'] as int?,
      SenseTime: json['SenseTime'] as String?,
      CommandTime: json['CommandTime'] as String?,
      AttendanceTime: json['AttendanceTime'] as String?,
      OnsiteArrivalTime: json['OnsiteArrivalTime'] as String?,
      ContactTime: json['ContactTime'] as String?,
      InvehicleTime: json['InvehicleTime'] as String?,
      StartOfTransportTime: json['StartOfTransportTime'] as String?,
      HospitalArrivalTime: json['HospitalArrivalTime'] as String?,
      FamilyContactTime: json['FamilyContactTime'] as String?,
      PoliceContactTime: json['PoliceContactTime'] as String?,
      TimeOfArrival: json['TimeOfArrival'] as String?,
      ReturnTime: json['ReturnTime'] as String?,
      TypeOfAccident: json['TypeOfAccident'] as String?,
      DateOfOccurrence: json['DateOfOccurrence'] as String?,
      TimeOfOccurrence: json['TimeOfOccurrence'] as String?,
      PlaceOfIncident: json['PlaceOfIncident'] as String?,
      AccidentSummary: json['AccidentSummary'] as String?,
      ADL: json['ADL'] as String?,
      TrafficAccidentClassification:
          json['TrafficAccidentClassification'] as String?,
      Witnesses: json['Witnesses'] as int?,
      BystanderCPR: json['BystanderCPR'] as String?,
      VerbalGuidance: json['VerbalGuidance'] as String?,
      ObservationTime: json['ObservationTime'] as String?,
      JCS: json['JCS'] as String?,
      GCSE: json['GCSE'] as String?,
      GCSV: json['GCSV'] as String?,
      GCSM: json['GCSM'] as String?,
      Respiration: json['Respiration'] as String?,
      Pulse: json['Pulse'] as String?,
      BloodPressureHigh: json['BloodPressureHigh'] as String?,
      BloodPressureLow: json['BloodPressureLow'] as String?,
      SpO2Percent: json['SpO2Percent'] as String?,
      SpO2Liter: json['SpO2Liter'] as String?,
      PupilRight: json['PupilRight'] as String?,
      PupilLeft: json['PupilLeft'] as String?,
      LightReflexRight: json['LightReflexRight'] as String?,
      PhotoreflexLeft: json['PhotoreflexLeft'] as String?,
      BodyTemperature: json['BodyTemperature'] as String?,
      FacialFeatures: json['FacialFeatures'] as String?,
      Hemorrhage: json['Hemorrhage'] as String?,
      Incontinence: json['Incontinence'] as String?,
      Vomiting: json['Vomiting'] as String?,
      Extremities: json['Extremities'] as String?,
      DescriptionOfObservationTime:
          json['DescriptionOfObservationTime'] as String?,
      SecuringAirway: json['SecuringAirway'] as String?,
      ForeignBodyRemoval: json['ForeignBodyRemoval'] as int?,
      Suction: json['Suction'] as int?,
      ArtificialRespiration: json['ArtificialRespiration'] as int?,
      ChestCompressions: json['ChestCompressions'] as int?,
      ECGMonitor: json['ECGMonitor'] as int?,
      O2Administration: json['O2Administration'] as int?,
      O2AdministrationTime: json['O2AdministrationTime'] as String?,
      SpinalCordMovementLimitation:
          json['SpinalCordMovementLimitation'] as String?,
      HemostaticTreatment: json['HemostaticTreatment'] as int?,
      AdductorFixation: json['AdductorFixation'] as int?,
      Coating: json['Coating'] as int?,
      BurnTreatment: json['BurnTreatment'] as int?,
      BSMeasurement1: json['BSMeasurement1'] as int?,
      BSMeasurementTime1: json['BSMeasurementTime1'] as String?,
      PunctureSite1: json['PunctureSite1'] as String?,
      BSMeasurement2: json['BSMeasurement2'] as int?,
      BSMeasurementTime2: json['BSMeasurementTime2'] as String?,
      PunctureSite2: json['PunctureSite2'] as String?,
      Other: json['Other'] as String?,
      PerceiverName: json['PerceiverName'] as String?,
      TypeOfDetection: json['TypeOfDetection'] as String?,
      CallerName: json['CallerName'] as String?,
      CallerTEL: json['CallerTEL'] as String?,
      MedicalTransportFacility: json['MedicalTransportFacility'] as String?,
      TransferringMedicalInstitution:
          json['TransferringMedicalInstitution'] as String?,
      TransferSourceReceivingTime:
          json['TransferSourceReceivingTime'] as String?,
      ReasonForTransfer: json['ReasonForTransfer'] as String?,
      ReasonForNotTransferring: json['ReasonForNotTransferring'] as String?,
      RecordOfRefusalOfTransfer: json['RecordOfRefusalOfTransfer'] as int?,
      Remark: json['Remark'] as String?,
      EntryName: json['EntryName'] as String?,
      EntryMachine: json['EntryMachine'] as String?,
      EntryDate: json['EntryDate'] as String?,
      UpdateName: json['UpdateName'] as String?,
      UpdateMachine: json['UpdateMachine'] as String?,
      UpdateDate: json['UpdateDate'] as String?,
      ReporterAffiliation: json['ReporterAffiliation'] as String?,
      ReportingClass: json['ReportingClass'] as String?,
      NameOfReporter: json['NameOfReporter'] as String?,
      AffiliationOfReporter: json['AffiliationOfReporter'] as String?,
      PositionOfReporter: json['PositionOfReporter'] as String?,
      SummaryOfOccurrence: json['SummaryOfOccurrence'] as String?,
    )
      ..FireStationName = json['FireStationName'] as String?
      ..OtherOfObservationTime = json['OtherOfObservationTime'] as String?;

Map<String, dynamic> _$DTReportToJson(DTReport instance) => <String, dynamic>{
      'ID': instance.ID,
      'TeamName': instance.TeamName,
      'TeamTEL': instance.TeamTEL,
      'FireStationName': instance.FireStationName,
      'TeamCaptainName': instance.TeamCaptainName,
      'LifesaverQualification': instance.LifesaverQualification,
      'WithLifeSavers': instance.WithLifeSavers,
      'TeamMemberName': instance.TeamMemberName,
      'InstitutionalMemberName': instance.InstitutionalMemberName,
      'Total': instance.Total,
      'Team': instance.Team,
      'SickInjuredPersonName': instance.SickInjuredPersonName,
      'SickInjuredPersonKANA': instance.SickInjuredPersonKANA,
      'SickInjuredPersonAddress': instance.SickInjuredPersonAddress,
      'SickInjuredPersonGender': instance.SickInjuredPersonGender,
      'SickInjuredPersonBirthDate': instance.SickInjuredPersonBirthDate,
      'SickInjuredPersonTEL': instance.SickInjuredPersonTEL,
      'SickInjuredPersonFamilyTEL': instance.SickInjuredPersonFamilyTEL,
      'SickInjuredPersonMedicalHistroy':
          instance.SickInjuredPersonMedicalHistroy,
      'SickInjuredPersonHistoryHospital':
          instance.SickInjuredPersonHistoryHospital,
      'SickInjuredPersonKakaritsuke': instance.SickInjuredPersonKakaritsuke,
      'SickInjuredPersonMedication': instance.SickInjuredPersonMedication,
      'SickInjuredPersonMedicationDetail':
          instance.SickInjuredPersonMedicationDetail,
      'SickInjuredPersonAllergy': instance.SickInjuredPersonAllergy,
      'SickInjuredPersonNameOfInjuaryOrSickness':
          instance.SickInjuredPersonNameOfInjuaryOrSickness,
      'SickInjuredPersonDegree': instance.SickInjuredPersonDegree,
      'SickInjuredPersonAge': instance.SickInjuredPersonAge,
      'SenseTime': instance.SenseTime,
      'CommandTime': instance.CommandTime,
      'AttendanceTime': instance.AttendanceTime,
      'OnsiteArrivalTime': instance.OnsiteArrivalTime,
      'ContactTime': instance.ContactTime,
      'InvehicleTime': instance.InvehicleTime,
      'StartOfTransportTime': instance.StartOfTransportTime,
      'HospitalArrivalTime': instance.HospitalArrivalTime,
      'FamilyContactTime': instance.FamilyContactTime,
      'PoliceContactTime': instance.PoliceContactTime,
      'TimeOfArrival': instance.TimeOfArrival,
      'ReturnTime': instance.ReturnTime,
      'TypeOfAccident': instance.TypeOfAccident,
      'DateOfOccurrence': instance.DateOfOccurrence,
      'TimeOfOccurrence': instance.TimeOfOccurrence,
      'PlaceOfIncident': instance.PlaceOfIncident,
      'AccidentSummary': instance.AccidentSummary,
      'ADL': instance.ADL,
      'TrafficAccidentClassification': instance.TrafficAccidentClassification,
      'Witnesses': instance.Witnesses,
      'BystanderCPR': instance.BystanderCPR,
      'VerbalGuidance': instance.VerbalGuidance,
      'ObservationTime': instance.ObservationTime,
      'JCS': instance.JCS,
      'GCSE': instance.GCSE,
      'GCSV': instance.GCSV,
      'GCSM': instance.GCSM,
      'Respiration': instance.Respiration,
      'Pulse': instance.Pulse,
      'BloodPressureHigh': instance.BloodPressureHigh,
      'BloodPressureLow': instance.BloodPressureLow,
      'SpO2Percent': instance.SpO2Percent,
      'SpO2Liter': instance.SpO2Liter,
      'PupilRight': instance.PupilRight,
      'PupilLeft': instance.PupilLeft,
      'LightReflexRight': instance.LightReflexRight,
      'PhotoreflexLeft': instance.PhotoreflexLeft,
      'BodyTemperature': instance.BodyTemperature,
      'FacialFeatures': instance.FacialFeatures,
      'Hemorrhage': instance.Hemorrhage,
      'Incontinence': instance.Incontinence,
      'Vomiting': instance.Vomiting,
      'Extremities': instance.Extremities,
      'DescriptionOfObservationTime': instance.DescriptionOfObservationTime,
      'OtherOfObservationTime': instance.OtherOfObservationTime,
      'SecuringAirway': instance.SecuringAirway,
      'ForeignBodyRemoval': instance.ForeignBodyRemoval,
      'Suction': instance.Suction,
      'ArtificialRespiration': instance.ArtificialRespiration,
      'ChestCompressions': instance.ChestCompressions,
      'ECGMonitor': instance.ECGMonitor,
      'O2Administration': instance.O2Administration,
      'O2AdministrationTime': instance.O2AdministrationTime,
      'SpinalCordMovementLimitation': instance.SpinalCordMovementLimitation,
      'HemostaticTreatment': instance.HemostaticTreatment,
      'AdductorFixation': instance.AdductorFixation,
      'Coating': instance.Coating,
      'BurnTreatment': instance.BurnTreatment,
      'BSMeasurement1': instance.BSMeasurement1,
      'BSMeasurementTime1': instance.BSMeasurementTime1,
      'PunctureSite1': instance.PunctureSite1,
      'BSMeasurement2': instance.BSMeasurement2,
      'BSMeasurementTime2': instance.BSMeasurementTime2,
      'PunctureSite2': instance.PunctureSite2,
      'Other': instance.Other,
      'PerceiverName': instance.PerceiverName,
      'TypeOfDetection': instance.TypeOfDetection,
      'CallerName': instance.CallerName,
      'CallerTEL': instance.CallerTEL,
      'MedicalTransportFacility': instance.MedicalTransportFacility,
      'TransferringMedicalInstitution': instance.TransferringMedicalInstitution,
      'TransferSourceReceivingTime': instance.TransferSourceReceivingTime,
      'ReasonForTransfer': instance.ReasonForTransfer,
      'ReasonForNotTransferring': instance.ReasonForNotTransferring,
      'RecordOfRefusalOfTransfer': instance.RecordOfRefusalOfTransfer,
      'Remark': instance.Remark,
      'EntryName': instance.EntryName,
      'EntryMachine': instance.EntryMachine,
      'EntryDate': instance.EntryDate,
      'UpdateName': instance.UpdateName,
      'UpdateMachine': instance.UpdateMachine,
      'UpdateDate': instance.UpdateDate,
      'ReporterAffiliation': instance.ReporterAffiliation,
      'ReportingClass': instance.ReportingClass,
      'NameOfReporter': instance.NameOfReporter,
      'AffiliationOfReporter': instance.AffiliationOfReporter,
      'PositionOfReporter': instance.PositionOfReporter,
      'SummaryOfOccurrence': instance.SummaryOfOccurrence,
    };
