dynamic data = {
  "DTReports": [
    {
      "FireStationName": "袖ヶ浦市消防本部",
      "ADL": "002",
      "AccidentSummary": "This is accident summary 1",
      "AdductorFixation": 1,
      "ArtificialRespiration": 1,
      "AttendanceTime": "06時30分",
      "BSMeasurement1": 12,
      "BSMeasurement2": 14,
      "BSMeasurementTime1": "06時30分",
      "BSMeasurementTime2": "06時30分",
      "BloodPressureHigh": "12, 12, 12",
      "BloodPressureLow": "8, 8, 8",
      "BodyTemperature": "30, 30, 30",
      "BurnTreatment": 1,
      "BystanderCPR": "06時30分",
      "CallerName": null,
      "CallerTEL": null,
      "ChestCompressions": 1,
      "Coating": 1,
      "CommandTime": "06時30分",
      "ContactTime": "06時30分",
      "DateOfOccurrence": "2022年07月14日",
      "DescriptionOfObservationTime": ", , ",
      "OtherOfObservationTime": ", , ",
      "ECGMonitor": 1,
      "EntryDate": null,
      "EntryMachine": null,
      "EntryName": null,
      "Extremities": "Extremities Test 1, Extremities Test 2, Extremities Test 3",
      "FacialFeatures": "003, 003, 003",
      "FamilyContactTime": "06時30分",
      "ForeignBodyRemoval": 1,
      "GCSE": "123,123,123",
      "GCSV": "123,123,123",
      "GCSM": "123,123,123",
      "Hemorrhage": "123,123,123",
      "HemostaticTreatment": 1,
      "HospitalArrivalTime": "06時30分",
      "ID": 1,
      "Incontinence": "003, 003, 003",
      "InstitutionalMemberName": null,
      "InvehicleTime": "06時30分",
      "JCS": "123,123,123",
      "LifesaverQualification": 0,
      "LightReflexRight": "0, 0, 0",
      "MedicalTransportFacility": null,
      "O2Administration": 1,
      "O2AdministrationTime": "06時30分",
      "ObservationTime": "06時30分, 06時30分, 06時30分",
      "OnsiteArrivalTime": "06時30分",
      "Other": "Other Test",
      "PerceiverName": null,
      "PhotoreflexLeft": "1, 1, 1",
      "PlaceOfIncident": "Place Of Incident",
      "PoliceContactTime": "06時30分",
      "Pulse": "12, 12, 12",
      "PunctureSite1": "Test 1",
      "PunctureSite2": "Test 2",
      "PupilLeft": "123, 123,123",
      "PupilRight": "123, 123, 123",
      "ReasonForNotTransferring": null,
      "ReasonForTransfer": null,
      "RecordOfRefusalOfTransfer": null,
      "Remark": null,
      "Respiration": "123, 123, 123",
      "ReturnTime": null,
      "SecuringAirway": "000",
      "SenseTime": "06時30分",
      "SickInjuredPersonAddress": "Ha Noi, Viet Nam",
      "SickInjuredPersonAge": null,
      "SickInjuredPersonAllergy": null,
      "SickInjuredPersonBirthDate": "1996年07月14日",
      "SickInjuredPersonDegree": null,
      "SickInjuredPersonFamilyTEL": "+84377732312",
      "SickInjuredPersonGender": "000",
      "SickInjuredPersonKANA": "TestKANA",
      "SickInjuredPersonKakaritsuke": null,
      "SickInjuredPersonMedication": null,
      "SickInjuredPersonMedicationDetail": "Sick Person Medication Detail",
      "SickInjuredPersonName": "Sick Person Name",
      "SickInjuredPersonNameOfInjuaryOrSickness": null,
      "SickInjuredPersonTEL": "+84377732311",
      "SickInjuredPersonMedicalHistroy": "Sick Medical Histroy",
      "SickInjuredPersonHistoryHospital": "Sick Person History Hospital",
      "SpO2Liter": "213, 23, 23",
      "SpO2Percent": "123, 123, 123",
      "SpinalCordMovementLimitation": "000",
      "StartOfTransportTime": "06時30分",
      "Suction": 1,
      "Team": null,
      "TeamCaptainName": "Captain Name Test",
      "TeamMemberName": null,
      "TeamName": "TeamName 1",
      "TeamTEL": "09032344234",
      "TimeOfArrival": null,
      "TimeOfOccurrence": "06時30分",
      "Total": null,
      "TrafficAccidentClassification": "002",
      "TransferSourceReceivingTime": null,
      "TransferringMedicalInstitution": null,
      "TypeOfAccident": "002",
      "TypeOfDetection": null,
      "UpdateDate": null,
      "UpdateMachine": null,
      "UpdateName": null,
      "VerbalGuidance": "Verbal Guidance Test",
      "Vomiting": "1, 1, 1",
      "WithLifeSavers": 1,
      "Witnesses": 0,
      "NameOfReporter": null,
      "AffiliationOfReporter": null,
      "PositionOfReporter": null,
      "SummaryOfOccurrence": null,
    }
  ],
  "MSTeamMembers": [
    {
      "TeamMemberCD": "000",
      "Name": "袖ヶ浦　ガウラ",
      "Position": "マスコットキャラクター",
      "TEL": "09012345678",
      "TeamCD": "000",
      "LifesaverQualification": 1,
    },
    {
      "TeamMemberCD": "001",
      "Name": "保科　久穂",
      "TEL": "09012341234",
      "TeamCD": "001",
      "LifesaverQualification": 0,
    },
    {
      "TeamMemberCD": "002",
      "Name": "大岡　慎弥",
      "TEL": "09022343234",
      "TeamCD": "001",
      "LifesaverQualification": 0,
    },
    {
      "TeamMemberCD": "003",
      "Name": "中村　健",
      "Position": "グループ長",
      "TEL": "09032344234",
      "TeamCD": "002",
      "LifesaverQualification": 1,
    },
    {
      "TeamMemberCD": "004",
      "Name": "鷹巣　良右",
      "Position": "部長",
      "TEL": "09032344235",
      "TeamCD": "001",
      "LifesaverQualification": 0,
    },
    {
      "TeamMemberCD": "005",
      "Name": "柳下　清隆",
      "Position": "グループ長",
      "TEL": "09032344236",
      "TeamCD": "001",
      "LifesaverQualification": 0,
    },
    {
      "TeamMemberCD": "006",
      "Name": "青木　栄介",
      "TEL": "09032344239",
      "TeamCD": "003",
      "LifesaverQualification": 0,
    },
    {
      "TeamMemberCD": "007",
      "Name": "松岡　和人",
      "TEL": "09032344238",
      "TeamCD": "001",
      "LifesaverQualification": 0,
    },
    {
      "TeamMemberCD": "008",
      "Name": "福島　隼人",
      "TEL": "09032344231",
      "TeamCD": "001",
      "LifesaverQualification": 0,
    },
    {
      "TeamMemberCD": "009",
      "Name": "袖ヶ浦　ソデリー",
      "Position": "マスコットキャラクター",
      "TEL": "09012345678",
      "TeamCD": "000",
      "LifesaverQualification": 1,
    },
    {
      "TeamMemberCD": "TMCD5678901234567890",
      "Name": "フル桁検証用氏名９０１２３４５６７８９０",
      "Position": "フル桁検証用役職９０１２３４５６７８９０",
      "TEL": "12345678901234567890",
      "TeamCD": "1--------01--------0",
      "LifesaverQualification": 1,
    }
  ],
  "MSTeams": [
    {"TeamCD": "000", "Name": "チームガウラ", "TEL": "09000000000", "FireStationCD":"001"},
    {"TeamCD": "001", "Name": "チーム鷹巣", "TEL": "09011111111", "FireStationCD":"001"},
    {"TeamCD": "002", "Name": "チーム中村", "TEL": "09022222222", "FireStationCD":"001"},
    {"TeamCD": "003", "Name": "チーム青木", "TEL": "09033333333", "FireStationCD":"001"},
    {"TeamCD": "1--------01--------0", "Name": "フル桁検証用チーム名１２３４５６７８９０", "TEL": "12345678901234567890", "FireStationCD":"001"}
  ],
  "MSFireStations": [
    {"FireStationCD": "000", "Name": "袖ヶ浦市消防本部", "Address": "千葉県袖ケ浦市福王台4丁目10番地7", "TEL": "0438-64-XXX9"},
    {"FireStationCD": "001", "Name": "袖ヶ浦市中央消防署", "Address": "千葉県袖ケ浦市福王台4丁目10番地7", "TEL": "0438-64-XXX5"},
    {"FireStationCD": "002", "Name": "袖ヶ浦市長浦消防署", "Address": "千葉県袖ケ浦市長浦580番地146", "TEL": "0438-62-XXX5"},
    {"FireStationCD": "003", "Name": "袖ヶ浦市平川消防署", "Address": "千葉県袖ケ浦市横田213番地", "TEL": "0438-75-XXX6"},
    {"FireStationCD": "004", "Name": "AZM消防署", "Address": "東京都港区西新橋2丁目1番1号", "TEL": "03-6205-XXX0"},
    {"FireStationCD": "005", "Name": "AK消防署", "Address": "東京都港区芝浦三丁目1番1号", "TEL": "03-6699-XXX0"},
    {"FireStationCD": "1--------01--------0", "Name": "フル桁消防署名８９０１２３４５６７８９０", "Address": "フル桁住所６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０", "TEL": "XXXXX-XXXXX-XXXXXXXXXX"}
  ],
  "MSHospitals": [
    {"HospitalCD": "000", "Name": "さくま耳鼻咽喉科医院", "Address": "千葉県袖ケ浦市神納617-1", "TEL": "0438-60-XXX7"},
    {"HospitalCD": "001", "Name": "かんのう整形外科", "Address": "千葉県袖ケ浦市神納689-1", "TEL": "0438-60-XXX7"},
    {"HospitalCD": "002", "Name": "わたなべ皮フ科形成外科クリニック", "Address": "千葉県袖ケ浦市神納707-1", "TEL": "0438-60-XXX1"},
    {"HospitalCD": "003", "Name": "田中医院", "Address": "千葉県袖ケ浦市神納2-10-7", "TEL": "0438-62-XXX0"},
    {"HospitalCD": "004", "Name": "福王台外科内科", "Address": "千葉県袖ケ浦市福王台1-10-9", "TEL": "0438-62-XXX1"},
    {"HospitalCD": "005", "Name": "福王台皮膚科歯科", "Address": "千葉県袖ケ浦市福王台2-1-5", "TEL": "0438-60-XXX8"},
    {"HospitalCD": "006", "Name": "菱沼医院", "Address": "千葉県袖ケ浦市福王台3-1-1", "TEL": "0438-62-XXX2"},
    {"HospitalCD": "007", "Name": "ヤマダ眼科クリニック", "Address": "千葉県袖ケ浦市奈良輪1-4-2", "TEL": "0438-62-XXX7"},
    {"HospitalCD": "008", "Name": "袖ケ浦医院", "Address": "千葉県袖ケ浦市奈良輪1-8-8", "TEL": "0438-62-XXX1"},
    {"HospitalCD": "009", "Name": "佐野医院", "Address": "千葉県袖ケ浦市奈良輪1-9-8", "TEL": "0438-62-XXX8"},
    {"HospitalCD": "010", "Name": "袖ケ浦クリニック", "Address": "千葉県袖ケ浦市奈良輪2-2-4", "TEL": "0438-60-XXX1"},
    {"HospitalCD": "011", "Name": "山口医院", "Address": "千葉県袖ケ浦市奈良輪535-1", "TEL": "0438-62-XXX6"},
    {"HospitalCD": "012", "Name": "袖ケ浦どんぐりクリニック", "Address": "千葉県袖ケ浦市袖ケ浦1-39-2", "TEL": "0438-63-XXX7"},
    {"HospitalCD": "013", "Name": "犬丸内科皮膚科クリニック", "Address": "千葉県袖ケ浦市蔵波2-28-5", "TEL": "0438-64-XXX1"},
    {"HospitalCD": "014", "Name": "石井内科小児科医院", "Address": "千葉県袖ケ浦市蔵波4-13-8", "TEL": "0438-62-XXX0"},
    {"HospitalCD": "015", "Name": "袖ケ浦メディカルクリニック", "Address": "千葉県袖ケ浦市蔵波4-20-9", "TEL": "0438-38-XXX5"},
    {"HospitalCD": "016", "Name": "蔵波台ハートクリニック", "Address": "千葉県袖ケ浦市蔵波5-17-2", "TEL": "0438-63-XXX0"},
    {"HospitalCD": "017", "Name": "田部整形外科", "Address": "千葉県袖ケ浦市蔵波5-19-7", "TEL": "0438-62-XXX5"},
    {"HospitalCD": "018", "Name": "よしだ胃腸内科クリニック", "Address": "千葉県袖ケ浦市蔵波6-1-5", "TEL": "0438-60-XXX1"},
    {"HospitalCD": "019", "Name": "Kenクリニック", "Address": "千葉県袖ケ浦市蔵波6-19-1", "TEL": "0438-64-XXX1"},
    {"HospitalCD": "020", "Name": "さつき台クリニック", "Address": "千葉県袖ケ浦市長浦駅1-7", "TEL": "0438-60-XXX7"},
    {"HospitalCD": "021", "Name": "長浦眼科クリニック", "Address": "千葉県袖ケ浦市長浦2-1-1", "TEL": "0438-63-XXX9"},
    {"HospitalCD": "022", "Name": "袖ケ浦さつき台病院", "Address": "千葉県袖ケ浦市長浦駅5-21", "TEL": "0438-62-XXX3"},
    {"HospitalCD": "023", "Name": "けやき台眼科", "Address": "千葉県袖ケ浦市代宿91", "TEL": "0438-64-XXX9"},
    {"HospitalCD": "024", "Name": "長浦泌尿器科クリニック", "Address": "千葉県袖ケ浦市久保田2863-1", "TEL": "0438-63-XXX2"},
    {"HospitalCD": "025", "Name": "平岡医院", "Address": "千葉県袖ケ浦市野里1773-1", "TEL": "0438-60-XXX7"},
    {"HospitalCD": "026", "Name": "高橋医院", "Address": "千葉県袖ケ浦市横田2624", "TEL": "0438-75-XXX7"},
    {"HospitalCD": "027", "Name": "井出医院", "Address": "千葉県袖ケ浦市横田3669", "TEL": "0438-75-XXX0"},
    {"HospitalCD": "1--------01--------0", "Name": "フル桁病院名７８９０１２３４５６７８９０", "Address": "フル桁住所６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０", "TEL": "XXXXX-XXXXX-XXXXXXXXXX"}
  ],
  "MSClassifications": [
    {"ClassificationCD": "001", "ClassificationSubCD": "000", "Value": "男", "Description": "性別"},
    {"ClassificationCD": "001", "ClassificationSubCD": "001", "Value": "女", "Description": "性別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "000", "Value": "急病", "Description": "事故種別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "001", "Value": "交通", "Description": "事故種別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "002", "Value": "一般", "Description": "事故種別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "003", "Value": "労災", "Description": "事故種別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "004", "Value": "自損", "Description": "事故種別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "005", "Value": "運動", "Description": "事故種別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "006", "Value": "転院", "Description": "事故種別"},
    {"ClassificationCD": "002", "ClassificationSubCD": "007", "Value": "その他", "Description": "事故種別"},
    {"ClassificationCD": "003", "ClassificationSubCD": "000", "Value": "自立", "Description": "ADL"},
    {"ClassificationCD": "003", "ClassificationSubCD": "001", "Value": "全介助", "Description": "ADL"},
    {"ClassificationCD": "003", "ClassificationSubCD": "002", "Value": "部分介助", "Description": "ADL"},
    {"ClassificationCD": "004", "ClassificationSubCD": "000", "Value": "シートベルト", "Description": "交通事故"},
    {"ClassificationCD": "004", "ClassificationSubCD": "001", "Value": "エアバック", "Description": "交通事故"},
    {"ClassificationCD": "004", "ClassificationSubCD": "002", "Value": "シートベルト＋エアバック", "Description": "交通事故"},
    {"ClassificationCD": "004", "ClassificationSubCD": "003", "Value": "チャイルドシート", "Description": "交通事故"},
    {"ClassificationCD": "004", "ClassificationSubCD": "004", "Value": "ヘルメット", "Description": "交通事故"},
    {"ClassificationCD": "004", "ClassificationSubCD": "005", "Value": "不明", "Description": "交通事故"},
    {"ClassificationCD": "005", "ClassificationSubCD": "000", "Value": "正常", "Description": "顔貌"},
    {"ClassificationCD": "005", "ClassificationSubCD": "001", "Value": "紅潮", "Description": "顔貌"},
    {"ClassificationCD": "005", "ClassificationSubCD": "002", "Value": "蒼白", "Description": "顔貌"},
    {"ClassificationCD": "005", "ClassificationSubCD": "003", "Value": "チアノーゼ", "Description": "顔貌"},
    {"ClassificationCD": "005", "ClassificationSubCD": "004", "Value": "発汗", "Description": "顔貌"},
    {"ClassificationCD": "005", "ClassificationSubCD": "005", "Value": "苦悶", "Description": "顔貌"},
    {"ClassificationCD": "006", "ClassificationSubCD": "000", "Value": "無", "Description": "失禁"},
    {"ClassificationCD": "006", "ClassificationSubCD": "001", "Value": "尿", "Description": "失禁"},
    {"ClassificationCD": "006", "ClassificationSubCD": "002", "Value": "便", "Description": "失禁"},
    {"ClassificationCD": "006", "ClassificationSubCD": "003", "Value": "尿＋便", "Description": "失禁"},
    {"ClassificationCD": "007", "ClassificationSubCD": "000", "Value": "用手", "Description": "気道確保"},
    {"ClassificationCD": "007", "ClassificationSubCD": "001", "Value": "エアウェイ", "Description": "気道確保"},
    {"ClassificationCD": "008", "ClassificationSubCD": "000", "Value": "頸椎のみ", "Description": "脊髄運動制限"},
    {"ClassificationCD": "008", "ClassificationSubCD": "001", "Value": "バックボード", "Description": "脊髄運動制限"},
    {"ClassificationCD": "009", "ClassificationSubCD": "1", "Value": "1:119固定", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "2", "Value": "2:119携帯", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "3", "Value": "3:119IP", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "4", "Value": "4:加入固定", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "5", "Value": "5:加入携帯", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "6", "Value": "6:加入IP", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "7", "Value": "7:警察電話", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "8", "Value": "8:駆け付け電話", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "9", "Value": "9:事後聞知", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "A", "Value": "A:事故覚知", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "B", "Value": "B:火災報知", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "C", "Value": "C:専用", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "D", "Value": "D:発信地", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "E", "Value": "E:消防無線", "Description": "覚知種別"},
    {"ClassificationCD": "009", "ClassificationSubCD": "Z", "Value": "Z:その他", "Description": "覚知種別"},
    {"ClassificationCD": "010", "ClassificationSubCD": "000", "Value": "無", "Description": "投薬"},
    {"ClassificationCD": "010", "ClassificationSubCD": "001", "Value": "有", "Description": "投薬"},
    {"ClassificationCD": "010", "ClassificationSubCD": "002", "Value": "手帳", "Description": "投薬"},
    {"ClassificationCD": "011", "ClassificationSubCD": "000", "Value": "０", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "001", "Value": "Ⅰ-1", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "002", "Value": "Ⅰ-2", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "003", "Value": "Ⅰ-3", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "004", "Value": "Ⅱ-10", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "005", "Value": "Ⅱ-20", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "006", "Value": "Ⅱ-30", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "007", "Value": "Ⅲ-100", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "008", "Value": "Ⅲ-200", "Description": "JCS"},
    {"ClassificationCD": "011", "ClassificationSubCD": "009", "Value": "Ⅲ-300", "Description": "JCS"},
    {"ClassificationCD": "012", "ClassificationSubCD": "000", "Value": "E1", "Description": "GCS-E"},
    {"ClassificationCD": "012", "ClassificationSubCD": "001", "Value": "E2", "Description": "GCS-E"},
    {"ClassificationCD": "012", "ClassificationSubCD": "002", "Value": "E3", "Description": "GCS-E"},
    {"ClassificationCD": "012", "ClassificationSubCD": "003", "Value": "E4", "Description": "GCS-E"},
    {"ClassificationCD": "013", "ClassificationSubCD": "000", "Value": "V1", "Description": "GCS-V"},
    {"ClassificationCD": "013", "ClassificationSubCD": "001", "Value": "V2", "Description": "GCS-V"},
    {"ClassificationCD": "013", "ClassificationSubCD": "002", "Value": "V3", "Description": "GCS-V"},
    {"ClassificationCD": "013", "ClassificationSubCD": "003", "Value": "V4", "Description": "GCS-V"},
    {"ClassificationCD": "013", "ClassificationSubCD": "004", "Value": "V5", "Description": "GCS-V"},
    {"ClassificationCD": "014", "ClassificationSubCD": "000", "Value": "M1", "Description": "GCS-M"},
    {"ClassificationCD": "014", "ClassificationSubCD": "001", "Value": "M2", "Description": "GCS-M"},
    {"ClassificationCD": "014", "ClassificationSubCD": "002", "Value": "M3", "Description": "GCS-M"},
    {"ClassificationCD": "014", "ClassificationSubCD": "003", "Value": "M4", "Description": "GCS-M"},
    {"ClassificationCD": "014", "ClassificationSubCD": "004", "Value": "M5", "Description": "GCS-M"},
    {"ClassificationCD": "014", "ClassificationSubCD": "005", "Value": "M6", "Description": "GCS-M"},
    {"ClassificationCD": "015", "ClassificationSubCD": "000", "Value": "M6", "Description": "観察時間説明"},
    {"ClassificationCD": "015", "ClassificationSubCD": "001", "Value": "M6 ", "Description": "観察時間説明"},
    {"ClassificationCD": "015", "ClassificationSubCD": "002", "Value": "M6   ", "Description": "観察時間説明"},
  ],
  "MSMessages": [
    {"CD": "001", "MessageType": "Warning", "MessageContent": "入力内容を保存せずに戻ります。よろしいですか？", "Button": "はい,」「キャンセル", "Purpose": "未登録終了確認"},
    {"CD": "002", "MessageType": "Question", "MessageContent": "入力内容を登録しますか？", "Button": "はい,キャンセル", "Purpose": "登録前確認"},
    {"CD": "003", "MessageType": "Information", "MessageContent": "登録処理を完了しました。", "Button": "OK", "Purpose": "登録後確認"},
    {"CD": "004", "MessageType": "Question", "MessageContent": "入力内容で更新しますか？", "Button": "はい,キャンセル", "Purpose": "更新前確認"},
    {"CD": "005", "MessageType": "Information", "MessageContent": "更新処理を完了しました。", "Button": "OK", "Purpose": "更新後確認"},
    {"CD": "006", "MessageType": "Error", "MessageContent": "入力項目]が未入力です。", "Button": "OK", "Purpose": "未入力エラー"}
  ]
};
